config/routes.rb
Rails.application.routes.draw do
  resources :experiences
  root 'experiences#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
	validate :experience
	 mount_uploader :experience, ExperienceUploader
	 default_scope { order('created_at DESC') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index 
    if params[:id]
      @experiences = Experience.where('id < ?', params[:id]).limit(10)
    else
      @experiences = Experience.limit(10)  
    end
    
    respond_to do |format|
      format.html
      format.js
    end
 
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url, notice: 'Experience was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
 
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:owner, :start_date, :end_date, :name, :description, :experience)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/_experience.html.erb
<div class="record " data-id="<%= experience.id %>">
  
        <div class="card border-info mb-3">
       	 <div class="card-header"> 
               <%= image_tag(experience.experience.url) unless experience.experience.blank?  %>
       	  <%= link_to experience.name, experience %>  <%= experience.description %> 
       	  </div> 
       	  <div class="card-body text-info">
       		  <%= experience.owner %> 
			  <%= experience.start_date %> 
			  <%= experience.end_date %>  
               </div> 
		  
       </div>
 </div>  

app/views/experiences/_form.html.erb
<%= form_with(model: experience, local: true) do |form| %>
  <% if experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% experience.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <div class="field">
    
    <%= form.file_field :experience, multipart: true, class: 'form-control' %>
  </div>
  <div class="field">
    <%= form.label :owner %>
    <%= form.number_field :owner, id: :experience_owner, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.text_field :start_date, id: :experience_start_date, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.text_field :end_date, id: :experience_end_date, class: 'form-control'%>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :experience_name, class: 'form-control' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :experience_description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit  class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<div class="container">
   <div class="row"> 
       <div class="col-md-12">  
					<h1>Editing Experience</h1>

					<%= render 'form', experience: @experience %>

					<%= link_to 'Show', @experience %> |
					<%= link_to 'Back', experiences_path %>
			</div> 
    </div>
 </div>

app/views/experiences/index.html.erb
<%= render 'partials/navbar' %>
<div class="container">
   <div class="row"> 
       <div class="col-md-12"> 
      	<div class="load-more-padding">
      		 <%= render @experiences %>   
      	</div> 
      </div>
    </div>
</div>


<div class=" load-more-container ">
  <%= image_tag "ajax-loader.gif", style: "display:none;", class: "loading-gif" %>
  <%= link_to "Load More", experiences_path, class: "load-more " %>
</div>

app/views/experiences/index.js.erb
// append the experiences partial to the div with class of container
$('.container').append('<%= escape_javascript(render(:partial => @experiences)) %>');

app/views/experiences/new.html.erb
<div class="container">
   <div class="row"> 
       <div class="col-md-12">  
				<h1>New Experience</h1>

				<%= render 'form', experience: @experience %>

				<%= link_to 'Back', experiences_path %>
			</div> 
    </div>
 </div>

app/views/experiences/show.html.erb
 <div class="experience_show">
   <div class="container">
     <div class="row">
       <div class="col-md-12">
                 
             
        <%= image_tag @experience.experience.url, class: 'img-fluid' %>
        <p>
          <strong>Owner:</strong>
          <%= @experience.owner %>
        </p>

        <p>
          <strong>Start date:</strong>
          <%= @experience.start_date %>
        </p>

        <p>
          <strong>End date:</strong>
          <%= @experience.end_date %>
        </p>

        <p>
          <strong>Name:</strong>
          <%= @experience.name %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @experience.description %>
        </p>

        <%= link_to 'Edit', edit_experience_path(@experience) %> |
        <%= link_to 'Back', experiences_path %>
          </div>
     </div>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Loadmore1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top"> 
    <%= link_to 'Experiences', root_path, class: ' navbar-brand' %>  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Home', root_path, class: 'nav-link' %> 
      </li>
      <li class="nav-item">
        <%= link_to 'New Experience', new_experience_path, class: 'btn btn-outline-info nav-link ' %>  
      </li>
      <li class="nav-item">
         <%= link_to "Load More", experiences_path, class: "load-more nav-link btn btn-outline-primary " %>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Contact</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav> 